#ifndef INGRESO_DE_LABORATORIO_H_INCLUDED
#define INGRESO_DE_LABORATORIO_H_INCLUDED
#include <stdio.h>
#include <stdlib.h>

///ESTRUCTURAS



///PROTOTIPADO


#endif // INGRESO_DE_LABORATORIO_H_INCLUDED
